diff_cont:
  ros__parameters:
    publish_rate: 50
    base_frame_id: base_link
    left_wheel_names: ['left_back_wheel_joint']
    right_wheel_names: ['right_back_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05 
    use_stamped_vel: false