controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_cont:
      type: diff_drive_controller/DiffDriveController 
      

  
  


    
    

  